steps:
  # Paso 1: Compilar la imagen usando el contexto de la raíz
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/medical-repo/retinia-app:latest', '.']

  # Paso 2: Subir la imagen al Artifact Registry creado
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/medical-repo/retinia-app:latest']

options:
  logging: CLOUD_LOGGING_ONLY